version: '3'
services:
  db:
    container_name: sql-server-maurevair
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssword
    ports:
      - '1433:1433'
    image: mcr.microsoft.com/mssql/server:2019-latest
